### ISSUE TITLE
Standalone Bazel build broken after switch to Python tables

### ISSUE THREAD

**Issue by emrekultursay** [google/perfetto#772]
The following change broke the standalone Bazel build:
   https://github.com/google/perfetto/commit/3df8a7e58102422ff2b8e52a465dabd3132e58d8 
    tp: migrate all table functions to use Python based tables

...it is causing this error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'bazel-out/k8-fastbuild/bin/external/perfetto/../perfetto_standalone/external/perfetto/src/trace_processor/tables/android_tables_py.h'
```

I created a clean Bazel project that only pulls Perfetto in standalone mode,  and did a binary search. The previous commit builds fine, but at that particular commit, we start getting the py.h errors.  A minimal repro workspace is attached. 
[perfetto_standalone.zip](https://github.com/google/perfetto/files/15135168/perfetto_standalone.zip)

Contents of simple `WORKSPACE` file:

```
$ cat WORKSPACE 
workspace(name = "perfetto_standalone")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
new_local_repository(
    name = "perfetto_cfg",
    path = "build/perfetto_overrides",
    build_file = "@perfetto_standalone//build/perfetto_overrides:BUILD",
)
http_archive(
    name = "perfetto",

    # THIS ONE WORKS:
    # Apr 24, 2023
    # 0c9981057a2d528a3619350a653ad78a9d5fc88b
    #url = "https://github.com/google/perfetto/archive/0c9981057a2d528a3619350a653ad78a9d5fc88b.zip",
    #strip_prefix = "perfetto-0c9981057a2d528a3619350a653ad78a9d5fc88b",

    # THIS ONE DOES NOT WORK:
    # Apr 24-25 in between, 2023
    # 3df8a7e58102422ff2b8e52a465dabd3132e58d8
    url = "https://github.com/google/perfetto/archive/3df8a7e58102422ff2b8e52a465dabd3132e58d8.zip",
    strip_prefix = "perfetto-3df8a7e58102422ff2b8e52a465dabd3132e58d8",
)

load("@perfetto_standalone//:deps.bzl", "perfetto_deps");
perfetto_deps()
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```

The error we get with standalone build:

```
$ CC=/usr/bin/clang-12 $BAZEL build @perfetto//:trace_processor_shell
INFO: Analyzed target @perfetto//:trace_processor_shell (24 packages loaded, 177 targets configured).
INFO: Found 1 target...
ERROR: /home/emrekultursay_google_com/.cache/bazel/_bazel_emrekultursay_google_com/272848397eeda72a9e3290173b4ea023/external/perfetto/BUILD:2048:22: Executing genrule @perfetto//:src_trace_processor_tables_tables_python_gen failed: (Exit 1): bash failed: error executing command (from target @perfetto//:src_trace_processor_tables_tables_python_gen) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/home/emrekultursay_google_com/.cache/bazel/_bazel_emrekultursay_google_com/272848397eeda72a9e3290173b4ea023/sandbox/linux-sandbox/1255/execroot/perfetto_standalone/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/perfetto/src_trace_processor_tables_tables_python_tool.runfiles/perfetto/tools/gen_tp_table_headers.py", line 103, in <module>
    sys.exit(main())
  File "/home/emrekultursay_google_com/.cache/bazel/_bazel_emrekultursay_google_com/272848397eeda72a9e3290173b4ea023/sandbox/linux-sandbox/1255/execroot/perfetto_standalone/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/perfetto/src_trace_processor_tables_tables_python_tool.runfiles/perfetto/tools/gen_tp_table_headers.py", line 94, in main
    with open(out_path, 'w', encoding='utf8') as out:
FileNotFoundError: [Errno 2] No such file or directory: 'bazel-out/k8-fastbuild/bin/external/perfetto/../perfetto_standalone/external/perfetto/src/trace_processor/tables/android_tables_py.h'
Target @perfetto//:trace_processor_shell failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/emrekultursay_google_com/.cache/bazel/_bazel_emrekultursay_google_com/272848397eeda72a9e3290173b4ea023/external/perfetto/BUILD:4851:19 Middleman _middlemen/@perfetto_S_S_Ctrace_Uprocessor_Ushell-BazelCppSemantics_build_arch_k8-fastbuild failed: (Exit 1): bash failed: error executing command (from target @perfetto//:src_trace_processor_tables_tables_python_gen) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 1.109s, Critical Path: 0.82s
INFO: 11 processes: 9 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by LalitMaganti** [comment]
https://r.android.com/3066342 should fix this.

**Comment by emrekultursay** [comment]
Using perfetto repo at head, the standalone build still fails. Can you take another look?

```
$ bazel build @perfetto//:trace_processor_shell 
INFO: Analyzed target @@perfetto//:trace_processor_shell (0 packages loaded, 0 targets configured).
ERROR: /usr/local/google/home/emrekultursay/.cache/bazel/_bazel_emrekultursay/5450d8248aaea21aedb8ab7f411448ee/external/perfetto/BUILD:5986:19: Compiling src/trace_processor/export_json.cc failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@perfetto//:trace_processor_shell) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++14' -MD -MF ... (remaining 95 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from bazel-out/k8-fastbuild/bin/external/perfetto/src/trace_processor/tables/android_tables_py.h:37,
                 from external/perfetto/src/trace_processor/storage/trace_storage.h:43,
                 from external/perfetto/src/trace_processor/export_json.h:24,
                 from external/perfetto/src/trace_processor/export_json.cc:18:
bazel-out/k8-fastbuild/bin/external/perfetto/src/trace_processor/tables/metadata_tables_py.h:37:10: fatal error: ../_main/external/perfetto/src/trace_processor/tables/metadata_tables_py.h: No such file or directory
   37 | #include "../_main/external/perfetto/src/trace_processor/tables/metadata_tables_py.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target @@perfetto//:trace_processor_shell failed to build
```

The error can be reproduced using the example in the sample attached above, with an updated `WORKSPACE` that has:

```
http_archive(
    name = "perfetto",
    url = "https://github.com/google/perfetto/archive/e42fee560e5e33687c275f6ec33d1b0dc9297dff.zip",
    strip_prefix = "perfetto-e42fee560e5e33687c275f6ec33d1b0dc9297dff",
)
```

**Comment by LalitMaganti** [comment]
https://r.android.com/3067905 should fix that: I forgot to also apply the same logic a bit later in the same file.
