### ISSUE TITLE
failed to build ui

### ISSUE THREAD

**Issue by zhangfanv** [google/perfetto#916]
![Image](https://github.com/user-attachments/assets/a22901b2-d794-43e4-bfe4-b917d00ee6bf)

**Comment by LalitMaganti** [comment]
Do you have Python installed? This is usually the error which shows up if you don't.

**Comment by zhangfanv** [comment]
Python installed. ![Image](https://github.com/user-attachments/assets/664b4832-8fc3-4d19-92fb-e63298e2100b)

**Comment by LalitMaganti** [comment]
Please provide the output of running the failing Python command manually. That will help debug a lot.

**Comment by zhangfanv** [comment]
When I directly run the command that failed using python3, it executes successfully, but it fails in ui/build.
![Image](https://github.com/user-attachments/assets/d3c580df-3e07-4195-bddc-e41d88465e65)

**Comment by zhangfanv** [comment]
![Image](https://github.com/user-attachments/assets/2b035cab-c047-4191-afd4-87f7c48ed985)

**Comment by LalitMaganti** [comment]
I believe this is the same issue as https://github.com/google/perfetto/issues/883. That is, you are running on a machine/VM which does not enable AVX.

To workaround this you can do:
```
tools/gn gen out/ui '--args "is_debug=false enable_perfetto_x64_cpu_opt=false"'
ui/build --no_override_gn_args
```

**Comment by zhangfanv** [comment]
It still fails when executed. I suspect that the structure of protoc is incorrect. When I directly run protoc, it prompts an error.

![Image](https://github.com/user-attachments/assets/cacbca64-b78b-40e9-9b7c-6270e55b6186)

**Comment by LalitMaganti** [comment]
There was a mistake previously. Please run:
```
tools/gn gen out/ui --args="is_debug=false enable_perfetto_x64_cpu_opt=false"
ui/build --no-override-gn-args
```

> When I directly run protoc, it prompts an error.

Yes the above should fix it

**Comment by zhangfanv** [comment]
It still fails when executed.

![Image](https://github.com/user-attachments/assets/9237dd88-51d1-4fb4-a219-6e431b0f9466)

**Comment by zhangfanv** [comment]
"Thank you very much for your reply. Now it has succeeded."

![Image](https://github.com/user-attachments/assets/b5448698-716c-4a55-9641-5faa13ee0bca)
